import { Product } from './types';

export const MOCK_CATALOG: Product[] = [
  {
    id: "1",
    brand_id: "Noorkari",
    name: "Ivory Georgette Chikankari Kurta Set",
    slug: "ivory-georgette-chikankari-kurta-set",
    description: "Hand-embroidered pure georgette Chikankari kurta with matching sharara. Features intricate shadow work by master artisans of Lucknow's old city.",
    price: 4500,
    category: "Kurta Set",
    fabric_type: "Georgette",
    craft_type: "Chikankari",
    occasions: ["festive", "day-wedding", "mehendi", "casual"],
    colors: ["ivory"],
    sizes_available: ["S", "M", "L", "XL"],
    images: ["https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=800&auto=format&fit=crop"],
    inventory_count: 10,
    is_active: true
  },
  {
    id: "2",
    brand_id: "Noorkari",
    name: "Emerald Green Silk Banarasi Saree",
    slug: "emerald-green-silk-banarasi-saree",
    description: "Classic Banarasi silk saree with authentic zari woven motifs in gold. Woven on handlooms in Varanasi — a heirloom piece meant to be passed down.",
    price: 12500,
    category: "Saree",
    fabric_type: "Silk",
    craft_type: "Banarasi",
    occasions: ["wedding", "reception", "evening", "festive"],
    colors: ["emerald green", "gold"],
    sizes_available: ["Free Size"],
    images: ["https://images.unsplash.com/photo-1610189013228-568eb4cace8a?q=80&w=800&auto=format&fit=crop"],
    inventory_count: 5,
    is_active: true
  },
  {
    id: "3",
    brand_id: "Nazakatai",
    name: "Pastel Pink Cotton Chikankari Anarkali",
    slug: "pastel-pink-cotton-chikankari-anarkali",
    description: "Soft cotton Anarkali set with delicate floral Chikankari motifs. Breathable, comfortable, and effortlessly elegant for summer celebrations.",
    price: 3800,
    category: "Anarkali",
    fabric_type: "Cotton",
    craft_type: "Chikankari",
    occasions: ["casual", "office", "day-wedding", "haldi"],
    colors: ["pastel pink"],
    sizes_available: ["XS", "S", "M", "L"],
    images: ["https://images.unsplash.com/photo-1630722288001-cff07abec514?q=80&w=800&auto=format&fit=crop"],
    inventory_count: 15,
    is_active: true
  },
  {
    id: "4",
    brand_id: "Nazakatai",
    name: "Royal Blue Zardozi Velvet Lehenga",
    slug: "royal-blue-zardozi-velvet-lehenga",
    description: "Stunning velvet lehenga adorned with heavy Zardozi hand-embroidery. A masterclass in regal luxury — crafted for grand wedding evenings.",
    price: 28000,
    category: "Lehenga",
    fabric_type: "Velvet",
    craft_type: "Zardozi",
    occasions: ["wedding", "bridal", "reception"],
    colors: ["royal blue", "gold"],
    sizes_available: ["S", "M", "L"],
    images: ["https://images.unsplash.com/photo-1595847326859-9941a54746f3?q=80&w=800&auto=format&fit=crop"],
    inventory_count: 2,
    is_active: true
  },
  {
    id: "5",
    brand_id: "Noorkari",
    name: "Yellow Organza Mukaish Suit",
    slug: "yellow-organza-mukaish-suit",
    description: "Lightweight organza suit with subtle mukaish mirror work catching the light beautifully. The perfect choice for Haldi ceremonies.",
    price: 6500,
    category: "Suit",
    fabric_type: "Organza",
    craft_type: "Mukaish",
    occasions: ["festive", "haldi", "day-wedding"],
    colors: ["yellow"],
    sizes_available: ["M", "L", "XL", "XXL"],
    images: ["https://images.unsplash.com/photo-1594958064972-005fa7fbf532?q=80&w=800&auto=format&fit=crop"],
    inventory_count: 8,
    is_active: true
  },
  {
    id: "6",
    brand_id: "Nazakatai",
    name: "Dusty Rose Silk Sharara Set",
    slug: "dusty-rose-silk-sharara-set",
    description: "Pure silk sharara set in a muted dusty rose — hand-block printed with traditional floral motifs. Quiet luxury at its finest.",
    price: 8900,
    category: "Kurta Set",
    fabric_type: "Silk",
    craft_type: "Block Print",
    occasions: ["festive", "reception", "day-wedding", "eid"],
    colors: ["dusty rose", "blush"],
    sizes_available: ["XS", "S", "M", "L", "XL"],
    images: ["https://images.unsplash.com/photo-1584488349132-72365a6c02cb?q=80&w=800&auto=format&fit=crop"],
    inventory_count: 7,
    is_active: true
  },
  {
    id: "7",
    brand_id: "Noorkari",
    name: "Ivory Straight-Cut Mukaish Kurta",
    slug: "ivory-straight-cut-mukaish-kurta",
    description: "Minimalist ivory straight kurta with delicate all-over mukaish buti work. Hand-finished Chikankari yoke. Quiet luxury in signature whites.",
    price: 5200,
    category: "Kurta Set",
    fabric_type: "Mulmul Cotton",
    craft_type: "Mukaish",
    occasions: ["casual", "office", "day-wedding", "eid"],
    colors: ["ivory", "white"],
    sizes_available: ["XS", "S", "M", "L", "XL", "XXL"],
    images: ["https://images.unsplash.com/photo-1596450514735-111a2fe02935?q=80&w=800&auto=format&fit=crop"],
    inventory_count: 20,
    is_active: true
  },
  {
    id: "8",
    brand_id: "Nazakatai",
    name: "Midnight Teal Georgette Anarkali",
    slug: "midnight-teal-georgette-anarkali",
    description: "Floor-length Anarkali in rich midnight teal georgette with delicate Chikankari floral trails. Effortlessly regal for evening occasions.",
    price: 7400,
    category: "Anarkali",
    fabric_type: "Georgette",
    craft_type: "Chikankari",
    occasions: ["reception", "wedding", "festive", "evening"],
    colors: ["teal", "midnight green"],
    sizes_available: ["S", "M", "L", "XL"],
    images: ["https://images.unsplash.com/photo-1583391733958-d25e77b2ce43?q=80&w=800&auto=format&fit=crop"],
    inventory_count: 6,
    is_active: true
  },
  {
    id: "9",
    brand_id: "Nazakatai",
    name: "Gold Zardozi Bridal Lehenga Set",
    slug: "gold-zardozi-bridal-lehenga-set",
    description: "A resplendent bridal lehenga in gold tissue fabric with dense Zardozi hand-embroidery. Worn by brides who believe in timeless grandeur.",
    price: 45000,
    category: "Lehenga",
    fabric_type: "Tissue Silk",
    craft_type: "Zardozi",
    occasions: ["wedding", "bridal", "reception"],
    colors: ["gold", "antique gold"],
    sizes_available: ["S", "M", "L"],
    images: ["https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=800&auto=format&fit=crop"],
    inventory_count: 1,
    is_active: true
  },
  {
    id: "10",
    brand_id: "Noorkari",
    name: "Lavender Chikankari Palazzo Set",
    slug: "lavender-chikankari-palazzo-set",
    description: "Breezy lavender palazzo set featuring hand-embroidered shadow Chikankari. Perfect for intimate garden celebrations and summer Mehndi ceremonies.",
    price: 4200,
    category: "Kurta Set",
    fabric_type: "Cotton",
    craft_type: "Chikankari",
    occasions: ["mehendi", "haldi", "casual", "festive"],
    colors: ["lavender", "lilac"],
    sizes_available: ["XS", "S", "M", "L", "XL"],
    images: ["https://images.unsplash.com/photo-1630722288001-cff07abec514?q=80&w=800&auto=format&fit=crop"],
    inventory_count: 12,
    is_active: true
  },
  {
    id: "11",
    brand_id: "Nazakatai",
    name: "Crimson Banarasi Silk Lehenga",
    slug: "crimson-banarasi-silk-lehenga",
    description: "Rich crimson Banarasi silk lehenga with woven gold butis and a grand dupatta. A wedding classic reimagined for the modern bride.",
    price: 22000,
    category: "Lehenga",
    fabric_type: "Banarasi Silk",
    craft_type: "Banarasi",
    occasions: ["wedding", "bridal", "festive"],
    colors: ["crimson", "red"],
    sizes_available: ["S", "M", "L"],
    images: ["https://images.unsplash.com/photo-1610189013228-568eb4cace8a?q=80&w=800&auto=format&fit=crop"],
    inventory_count: 3,
    is_active: true
  },
  {
    id: "12",
    brand_id: "Noorkari",
    name: "Sage Green Phulkari Dupatta Suit",
    slug: "sage-green-phulkari-dupatta-suit",
    description: "Contemporary straight suit in sage green with a vibrant Phulkari embroidered dupatta. A celebration of Punjab's rich textile heritage.",
    price: 5800,
    category: "Suit",
    fabric_type: "Chanderi",
    craft_type: "Phulkari",
    occasions: ["festive", "casual", "day-wedding", "eid"],
    colors: ["sage green"],
    sizes_available: ["XS", "S", "M", "L", "XL", "XXL"],
    images: ["https://images.unsplash.com/photo-1584488349132-72365a6c02cb?q=80&w=800&auto=format&fit=crop"],
    inventory_count: 9,
    is_active: true
  }
];
