import { Product } from './types';

export const MOCK_CATALOG: Product[] = [
  {
    id: "1",
    brand_id: "noorkari",
    name: "Ivory Georgette Chikankari Kurta Set",
    slug: "ivory-georgette-chikankari-kurta-set",
    description: "Hand-embroidered pure georgette Chikankari kurta with matching sharara. Features intricate shadow work.",
    price: 4500,
    category: "Kurta Set",
    fabric_type: "Georgette",
    craft_type: "Chikankari",
    occasions: ["festive", "day-wedding", "casual"],
    colors: ["ivory"],
    sizes_available: ["S", "M", "L", "XL"],
    images: ["https://images.unsplash.com/photo-1583391733958-d25e61c2c366?auto=format&fit=crop&q=80&w=600"],
    inventory_count: 10,
    is_active: true
  },
  {
    id: "2",
    brand_id: "noorkari",
    name: "Emerald Green Silk Banarasi Saree",
    slug: "emerald-green-silk-banarasi-saree",
    description: "Classic Banarasi silk saree with authentic zari woven motifs. Perfect for evening occasions.",
    price: 12500,
    category: "Saree",
    fabric_type: "Silk",
    craft_type: "Banarasi",
    occasions: ["wedding", "evening", "festive"],
    colors: ["emerald green", "gold"],
    sizes_available: ["Free Size"],
    images: ["https://images.unsplash.com/photo-1610189013228-568eb4cace8a?auto=format&fit=crop&q=80&w=600"],
    inventory_count: 5,
    is_active: true
  },
  {
    id: "3",
    brand_id: "nazakatai",
    name: "Pastel Pink Cotton Chikankari Anarkali",
    slug: "pastel-pink-cotton-chikankari-anarkali",
    description: "Soft cotton Anarkali set with delicate floral Chikankari motifs. Breathable and comfortable.",
    price: 3800,
    category: "Anarkali",
    fabric_type: "Cotton",
    craft_type: "Chikankari",
    occasions: ["casual", "office", "day-wedding"],
    colors: ["pastel pink"],
    sizes_available: ["XS", "S", "M", "L"],
    images: ["https://images.unsplash.com/photo-1630722288001-cff07abec514?auto=format&fit=crop&q=80&w=600"],
    inventory_count: 15,
    is_active: true
  },
  {
    id: "4",
    brand_id: "nazakatai",
    name: "Royal Blue Zardozi Velvet Lehenga",
    slug: "royal-blue-zardozi-velvet-lehenga",
    description: "Stunning velvet lehenga adorned with heavy Zardozi hand-embroidery. A masterclass in luxury.",
    price: 28000,
    category: "Lehenga",
    fabric_type: "Velvet",
    craft_type: "Zardozi",
    occasions: ["wedding", "bridal"],
    colors: ["royal blue"],
    sizes_available: ["S", "M", "L"],
    images: ["https://images.unsplash.com/photo-1595847326859-9941a54746f3?auto=format&fit=crop&q=80&w=600"],
    inventory_count: 2,
    is_active: true
  },
  {
    id: "5",
    brand_id: "noorkari",
    name: "Yellow Organza Silk Suit",
    slug: "yellow-organza-silk-suit",
    description: "Lightweight organza suit with subtle mukaish work. Ideal for Haldi ceremonies.",
    price: 6500,
    category: "Suit",
    fabric_type: "Organza",
    craft_type: "Mukaish",
    occasions: ["festive", "haldi", "day-wedding"],
    colors: ["yellow"],
    sizes_available: ["M", "L", "XL", "XXL"],
    images: ["https://images.unsplash.com/photo-1594958064972-005fa7fbf532?auto=format&fit=crop&q=80&w=600"],
    inventory_count: 8,
    is_active: true
  }
];
